# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude

title: Dopuskh3
author:
  name: dopuskh3
  email: f.visconte@gmail.com
  github: dopuskh3
  twitter: dopuskh3
  bio: My github notepad
  email_md5: 726351295ec82e145928582f595aa3aa
  
BASE_PATH: /

categories_path: categories.html
tags_path: tags.html
